- Gui/Clipboard/Clipboard.cs
- Gui/Clipboard/ISystemClipboard.cs
- Gui/Gui.csproj
- PlatformWin32/PlatformWin32.csproj
- PlatformWin32/win32/WidgetForWindowsFormsAbstract.cs
- PlatformWin32/win32/WindowsFormsClipboard.cs
Adds support for Mac specific clipboard implementation to work around Mono clipboard issues
> Abstract Clipboard for better platform specific support

- agg/PluginFinder.cs
For more details on the process see:
http://inside.matterhackers.com/MatterControl_Android#debuggable
> Add symbol support for debugging Android plugins

- PlatformWin32/win32/WindowsFormsOpenGL.cs
- RenderOpenGl/GL.cs
Sets gl to used gpu buffers or store buffers on memory according to if gl driver contains glGenBuffers
> Checks if GL Drivers supports buffers

- PlatformWin32/win32/WindowsFormsOpenGL.cs
Moved Checking of cpu capabilities to be in MyGLControl constructor
> Fixed location of checking cpu capabilities 

- SerialPortCommunication/FrostedSerial/FrostedSerialPortFactory.cs
- examples/GCodeVisualizer/GCodeFileLoaded.cs
Added Timelock on get availableFactories for generating Driver
Added M Commands to list of valid for debug
> X3G Driver changes

- SerialPortCommunication/FrostedSerial/CSharpSerialPortWrapper.cs
- SerialPortCommunication/FrostedSerial/IFrostedSerialPort.cs
CSharpSerialPort implements Read and Write using byte arrays
> IFrostedSerial Declares Read and Write using byte arrays

- PolygonMesh/Processors/AmfProcessing.cs
- PolygonMesh/Processors/MeshFileIo.cs
- PolygonMesh/VertexCollection.cs
- Remove AMF vertex validation
> Initial work for AMF progress reporting

- Gui/GUIWidget.cs
- Gui/Menu/DropDownList.cs
- Gui/Menu/Menu.cs
- Gui/Menu/MenuItemStatesView.cs
- Gui/Menu/OpenMenuContents.cs
- Highlight current selection in droplist
- Add mechanism to clear current highlight
- Refactor droplist classes to use auto properties
- Make ShowMenu protected, virtual so droplist can override
- Add Parents<T>(), Children<T>() extension methods to GuiWidget
- DRY up MenuItem.Highlighted logic and expose for reuse in DropDownList
> Highlight and scroll to current droplist selection

- Gui/UiThread.cs
- PlatformWin32/win32/ImageIOWindowsPlugin.cs
- PlatformWin32/win32/WidgetForWindowsFormsAbstract.cs
- PlatformWin32/win32/WindowsFormsAbstract.cs
- Tests/Agg.Tests/Agg.UI/MenuTests.cs
- Tests/Agg.Tests/Agg.UI/ToolTipTests.cs
- Update UIThread/OnIdle nomenclature
>  Limit timer driven OnIdle invocations

- PlatformWin32/win32/WindowsFormsOpenGL.cs
- examples/GCodeVisualizer/GCodeFileLoaded.cs
added GCommands for MakerBot to command White list
> Updated Graphics driver checked

- Localizations/TranslationMap.cs
- Use backing fields
- Use single dictionary for translation
- Prevent file generation in Release
> Refactor TranslationMap

- PolygonMesh/Mesh.cs
- Use auto properties
- Revise member ordering guidelines
> Refactor for clarity

- Gui/GUIWidget.cs
- OpenGlGui/TrackballTumbleWidget.cs
- examples/MeshViewer/MeshViewerWidget.cs
- Add TransformFromScreenSpace function to GuiWidget
- Rename GetRayForLocalBounds to better convey behavior
> Revise drag item positioning

- DataConverters3D/DataConverters3D.csproj
- DataConverters3D/Object3D/IObject3D.cs
- DataConverters3D/Object3D/InteractiveScene.cs
- DataConverters3D/Object3D/Json/MatrixConverter.cs
- DataConverters3D/Object3D/Json/Object3DConverter.cs
- DataConverters3D/Object3D/Object3D.cs
- DataConverters3D/Object3D/Object3DExtensions.cs
- DataConverters3D/Object3D/PlatingData.cs
- Gui/GUIWidget.cs
- examples/MeshViewer/MeshViewer.csproj
- examples/MeshViewer/MeshViewerWidget.cs
- Add TopmostParent method to GuiWidget
- Reuse TopmostParent in TransformFromScreenSpace and drag/drop
- Consolidate file/mesh loading implementations
- Bust out Object3D classes into separate files
- Move all Object3D types to a common assembly
> Revise and extend drag/drop functionality

- DataConverters3D/DataConverters3D.csproj
- DataConverters3D/Object3D/IObject3D.cs
- DataConverters3D/Object3D/TextObject.cs
- Gui/RadioButton/RadioButton.cs
- agg/PluginFinder.cs
- Add TextObject for Braille/Text creators
- Guard for null experienced when closing child radio buttons
- Add Interface loading support to PluginFinder
> Text Creator updates

- DataConverters3D/AmfProcessing.cs
- DataConverters3D/Object3D/IObject3D.cs
- DataConverters3D/Object3D/InteractiveScene.cs
- DataConverters3D/Object3D/Object3D.cs
- DataConverters3D/Object3D/Object3DExtensions.cs
- examples/MeshViewer/MeshViewerWidget.cs
Add compatibility with official amf sample files
> Switch IObject3D to use Mesh instead of MeshGroup

- GuiAutomation/AutomationRunner.cs
- Tests/Agg.Tests/Agg/WidgetClickTests.cs
- Add helper method to AutomationRunner for local coordinates
- Add mouse automation for mouse[up/down] tests
- Add TestHostWindow helper class to return test data from execution
- Add failing test for known problem behavior
- Revise up/down tests for clarity
> Revise Click tests

- Gui/Menu/DropDownList.cs
* Proxy TextColor property to child TextWidget
* Use initializer syntax
* Use lambdas for events
* Remove dead code
* Gen arrow glyph during construction rather than per draw
* Consolidate drawing code
> Refactor DropDownList

- Tests/Agg.Tests/Agg.UI/MenuTests.cs
- Conditionally compile breaking tests
> Get updated profiles compiling on Android

- Gui/Menu/DropDownList.cs
- Gui/Menu/Menu.cs
> Fix droplist issues - invalid padding, won't expand

- Gui/TextWidgets/WrappedTextWidget.cs
- agg/Font/TextWrapping.cs
- agg/Font/TypeFacePrinter.cs
Working to improve speed of text wrapping.
> Option to make wrap test not double buffer

- AggTests/AggTests.csproj
- AggTests/packages.config
- examples/AllDemos.sln
- Revert AggTests.csproj to Nunit 2.6.4
- Add Agg.Tests project to AllDemos.sln
> Updates for AppVeyor

- agg/Font/StyledTypeFace.cs
- agg/Font/TextWrapping.cs
- agg/Font/TypeFacePrinter.cs
Made it easier to get the correct kerning
> Made text wrapping faster

- examples/GCodeVisualizer/Renderer/GCodeRenderer.cs
- examples/GCodeVisualizer/Renderer/RenderFeatures/RenderFeatureExtrusion.cs
increase the rejected move length (to reduce rounding errors)
> Make it possible to change the expected nozzle size

- GuiAutomation/AutomationRunner.cs
> Added a Drop function without a target

- Gui/TextWidgets/WrappedTextWidget.cs
- Tests/Agg.Tests/Agg/FontTests.cs
- Tests/Agg.Tests/Agg/WidgetClickTests.cs
- agg/Font/TextWrapping.cs
Made the default control not include consideration for a scroll bar
Made a new test for English text wrapping
> Fixed a bug with text wrapping happening early

- Gui/TextWidgets/UndoBuffer.cs
Added a AddAndDo function to UndoBuffer
> Added a new class to do undo that takes tow actions.

- GuiAutomation/AggInputMethods.cs
- GuiAutomation/AutomationRunner.cs
- GuiAutomation/NativeMethods.cs
- GuiAutomation/WindowsInputMethods.cs
- PlatformWin32/win32/HookWindowsInputAndSendToWidget.cs
- Remove InputMethod base class, use IInputMethod interface replacement
- Improve AggInputMethod to invalidate and better depict interaction
- Remove dead code
- Fix typos
> Extract NativeMethods to standalone class

- GtkFileDialogs/FileDialogPlugin.cs
- GtkFileDialogs/GtkFileDialogs.csproj
- GtkFileDialogs/Properties/AssemblyInfo.cs
Making a pull request for this just to keep it on the radar. John, I added a condition to the .csproj file that should keep it from building on Windows. Could you try it out?
> GTK file dialogs for Linux

- Gui/Themes/ActiveTheme.cs
- Gui/Themes/ThemeColors.cs
> Set theme name

- Gui/Menu/DropDownList.cs
- Gui/Themes/ActiveTheme.cs
ActiveTheme does not recreate its data all the time
issue #155
> Renamed ActiveTheme.Instance to Current

- Gui/GUIWidget.cs
- GuiAutomation/AutomationRunner.cs
- agg/agg_basics.cs
Added WaitUntil function on Automation Runner
Added some documentation
> Added fire and forget for task

- PlatformAbstract/IStaticData.cs
- PolygonMesh/Net3dBool/Face.cs
- PolygonMesh/Net3dBool/Line.cs
- PolygonMesh/Net3dBool/Object3D.cs
- RayTracer/Primitive/BoundingVolumeHierarchy.cs
- RayTracer/Primitive/Shapes/Cylinder.cs
- RayTracer/Primitive/Shapes/PlaneShape.cs
- RayTracer/RayTracer.cs
- RayTracer/TraceData/Frustum.cs
- RayTracer/TraceData/RayBundle.cs
- Tests/Agg.Tests/Agg.RayTracer/FrustumTests.cs
- VectorMath/Plane.cs
Working on new ray trace bundles
> Wrote a DownloadToImageAsync function in in StaticData

- Gui/ImageWidget.cs
- PlatformAbstract/IStaticData.cs
- agg/Image/ImageBuffer.cs
Made image widget resize with the image it contains.
> Made DownloadToImageAsync able to use downloaded image size

- Tests/Agg.Tests/Agg.UI/AutomationTesterHarness.cs
- agg/agg_basics.cs
- Add details to test output describing the unexpected exception
- Remove FireAndForget extension method
> Add exception handling to callback function execution

- AggTests/AggTests.csproj
- AggTests/packages.config
- GuiAutomation/AutomationRunner.cs
- Localizations/TranslationMap.cs
- Tests/Agg.Tests/Agg.PolygonMesh/MeshTests.cs
- Tests/Agg.Tests/Agg.Tests.csproj
- Tests/Agg.Tests/app.config
- Tests/Agg.Tests/packages.config
- examples/AllDemos.sln
- Revise hard-coded paths for compatibility with new VS adapter
- Add utility functions for path generation
> Upgrade to NUnit3

- GuiAutomation/AutomationRunner.cs
- Tests/Agg.Tests/Agg.UI/AutomationTesterHarness.cs
- Add reasonable default value for WaitForName
- Use properties instead of fields
- Use correct casing
- Log test results to console in AddTestResult (+1 squashed commits)
- Improve parameter names
> Revise automation components

- Tests/Agg.Tests/Agg.UI/AutomationTesterHarness.cs
- Move nested type below class members
> Remove NUnit2 StackTrace workaround

- Gui/Menu/DropDownList.cs
- Gui/Menu/OpenMenuContents.cs
- Fix regression with highlighted item not drawn due to incorrect StatesView
> Add DropList filtering support

- Gui/Menu/DropDownList.cs
- Add down arrow keybindings to open droplist
- Add arrow keybindings for navigating in visible droplist
- Add automatic first item highlighting if SelectedIndex not set
- Add MenuItem extension function for setting StatesView highlight
> Refine and extend DropList keyboard interactions

- PlatformWin32/win32/FileSystemStaticData.cs
- Tests/Agg.Tests/Agg.UI/AutomationTesterHarness.cs
- Improve NUnit console output
> Revise test output formatting

- Gui/CheckBox/CheckBoxViewText.cs
MatterHackers/MCCentral#511
Seems to fix the checkbox/label alignment on desktop.
However I am not completely sure this is an all encompassing fix
and it should be reviewed by Lars.
> Fixed alignment of checkboxes and checkbox labels on desktop

- Tests/Agg.Tests/Agg.Tests.csproj
- Tests/Agg.Tests/packages.config
- Issue MatterHackers/MCCentral#525
> Upgrade to latest NUnit.ApplicationDomain package

- Gui/Themes/ActiveTheme.cs
> The magenta in color is no longer being selected

- AggTests/AggTests.csproj
- Gui/GUIWidget.cs
- GuiAutomation/AutomationRunner.cs
- NuGet.config
- Tests/Agg.Tests/Agg.Tests.csproj
- Tests/Agg.Tests/Agg.UI/AutomationRunnerTests.cs
- Tests/Agg.Tests/Agg.UI/MenuTests.cs
- Tests/Agg.Tests/Agg.UI/MouseInteractionTests.cs
- Tests/Agg.Tests/Agg.UI/TextEditTests.cs
- Tests/Agg.Tests/Agg.UI/ToolTipTests.cs
- Tests/Agg.Tests/Agg/WidgetClickTests.cs
- Tests/Agg.Tests/packages.config
- examples/AllDemos.sln
- Add new 'AutomationTest' delegate - func(AutomationRunner, Task)
- Revise ShowWindowAndExecuteTests for Asserts and async test methods
- Migrate RunInApplicationDomain attributes to TextFixture
- Convert from Action<AutomationRunner> to AutomationTest delegate
- Convert testRunner.AddTestResult to Assert.IsTrue
- Remove Assert.IsTrue(testRunner.AllTestPassed(n)) - use Asserts
- Add return Task.FromResult(0) for non-async test method bodies
- Upgrade NUnit.ApplicationDomain to v10
> Revise Agg automation

- PlatformWin32/win32/HookWindowsInputAndSendToWidget.cs
- Issue MatterHackers/MCCentral#687
> Remap Cancel keycode to Enter on OS X

- Tests/Agg.Tests/Agg.UI/TextEditTests.cs
- Add assert messages for troubleshooting
- Reorder prep code
- Add FixNeeded comment for VerifyFocusProperty test
> Revise failing SelectAllOnFocusCanStillClickAfterSelection test

- Gui/FileDialogs/FileDialog.cs
- Issue MatterHackers/MCCentral#737
> Reuse OpenFileDialog for SaveFileDialog

- GuiAutomation/AutomationRunner.cs
- Tests/Agg.Tests/Agg/WidgetClickTests.cs
- Allows for code bound via RunOnIdle to complete before returning
> Wait in ClickByName automation function before returning to caller

- RenderOpenGl/GL.cs
- RenderOpenGl/ImageGlPlugin.cs
Don't crash if trying to get an gl image plugin when in software mode.
> Made HardwareAvailable a propertie

- Gui/Menu/DropDownList.cs
- Gui/Menu/MenuItem.cs
- Gui/PerformanceTimer/PerformancePanel.cs
- Issue MatterHackers/MCCentral#908
ReloadAll fires when "Add New Printer" is selected
- Issue MatterHackers/MCCentral#943
> Expose option for non-selectable DropDownList MenutItems

- Gui/GUIWidget.cs
- Tests/Agg.Tests/Agg.UI/AutomationRunnerTests.cs
- Tests/Agg.Tests/Agg.UI/MouseInteractionTests.cs
Deleted fixed needed tests with no body
> Fixed mouse down interactions to set correct states.

- Gui/FileDialogs/AutomationFileDialogCreator.cs
- Gui/FileDialogs/FileDialog.cs
- Gui/Gui.csproj
Revise naming to better clarify behavior:
- AggFileDialogCreator  -> AutomationFileDialogCreator
> Extract automation DialogCreator to standalone file

- Gui/FileDialogs/FileDialogCreator.cs
- Gui/Gui.csproj
- Gui/SystemWindow/SystemWindow.cs
- Gui/SystemWindow/SystemWindowCreatorPlugin.cs
- PlatformAbstract/IStaticData.cs
- WindowsFileDialogs/FileDialogPlugin.cs
- Refactor to improve pending commit/rename history results
> Extract FileDialogCreator to file

- GuiAutomation/AutomationRunner.cs
- examples/MeshViewer/MeshViewerWidget.cs
Don't select 3d controls when not visible
> drag drop can set mouse button

- RayTracer/Primitive/Transform.cs
- Child is null in some scenarios
> Guard against null ref

- Gui/Menu/DropDownList.cs
- Tests/Agg.Tests/Agg.Gaming/Vector2D.cs
- Tests/Agg.Tests/Agg.Gaming/Vector3D.cs
- Tests/Agg.Tests/Agg.UI/AutomationRunnerTests.cs
- Tests/Agg.Tests/Agg.UI/MenuTests.cs
- Tests/Agg.Tests/Agg/WidgetClickTests.cs
- Issue MatterHackers/MCCentral#1066
Investigate failing FixNeeded Tests
> FixNeeded test updates

- Gui/MessageBox.cs
- Gui/ProgressControl.cs
- Gui/SystemWindow/AbstractOsMappingWidget.cs
- Gui/SystemWindow/SystemWindow.cs
- ImageProcessing/WhiteToColor.cs
- PlatformWin32/win32/SystemWindowCreator_WindowsForms.cs
- examples/GCodeVisualizer/GCodeViewWidget.cs
- Issue MatterHackers/MCCentral#1118
Add "event" keyword to all public EventHandler fields
> Convert public EventHandler fields to events

- Gui/SystemWindow/AbstractOsMappingWidget.cs
- Gui/SystemWindow/SystemWindow.cs
- PlatformWin32/win32/OsInformationWindowsPlugin.cs
- PlatformWin32/win32/SystemWindowCreator_WindowsForms.cs
- PlatformWin32/win32/WidgetForWindowsFormsOpenGL.cs
- PlatformWin32/win32/WindowsFormsAbstract.cs
- Issue MatterHackers/MCCentral#1127
Fix startup window sizing
> Revise window auto-centering, add maximize persistence

- Gui/ProgressControl.cs
- Issue MatterHackers/MCCentral#1148
Unexpected thrown exception during render
> Restrict ProgressBar fill to valid values

- SerialPortCommunication/FrostedSerial/FrostedSerialPortFactory.cs
- Issue MatterHackers/MCCentral#1306
System.FormatException: An invalid IP address was specified
> Move PortIsAvailable logic into PortFactory

- AggTests/AggTests.csproj
- Gaming/Gaming.csproj
- NeuralNet/NeuralNet.csproj
- examples/FloodFill/FloodFill.csproj
- examples/FontHinting/FontHinting.csproj
- examples/GUITester/GUITester.csproj
- examples/HelloWorld/HelloWorld.csproj
- examples/LionShape/LionShape.csproj
- examples/MomsSolitaire/MomsSolitaire.csproj
- examples/PolygonClipping/PolygonClipping.csproj
- examples/RockBlaster/RockBlaster.csproj
- examples/SmartSweepers/SmartSweepers.csproj
- examples/aa_demo/aa_demo.csproj
- examples/aa_test/aa_test.csproj
- examples/alpha_mask2/alpha_mask2.csproj
- examples/blur/blur.csproj
- examples/component_rendering/component_rendering.csproj
- examples/gouraud/gouraud.csproj
- examples/gouraud_mesh/gouraud_mesh.csproj
- examples/gradients/gradients.csproj
- examples/image1/image1.csproj
- examples/image_filters/image_filters.csproj
- examples/image_resample/image_resample.csproj
- examples/line_patterns/line_patterns.csproj
- examples/lion/lion.csproj
- examples/lion_outline/lion_outline.csproj
- examples/perspective/perspective.csproj
- examples/rounded_rect/rounded_rect.csproj
- examples/trans_curve1/trans_curve1.csproj
- Issue MatterHackers/MCCentral#1341
MSBuild reports 138 'Processor architecture mismatch' errors in AllDemos.sln
> Consistent PlatformTarget across projects and dependencies

- Gui/agg_gamma_ctrl.cs
> Resolve CS0618 - 'gsv_text' is obsolete

- GtkFileDialogs/FileDialogPlugin.cs
Fixes https://github.com/MatterHackers/MatterControl/issues/2011
> Fixed crash on KDE

- Gui/GUIWidget.cs
- Gui/Menu/Menu.cs
- Gui/Menu/MenuItemStatesView.cs
- Gui/Menu/OpenMenuContents.cs
- examples/MeshViewer/MeshViewerWidget.cs
- Extract core popup logic to PopupWidget
- Revise PopupMenu to contain just menu related logic
- Make PopupWiget public and reusable
- Use is operator instead of (as x != null)
- Fix typos
> Rename OpenMenuContents to PopupMenu

- Gui/Menu/Menu.cs
- Gui/Menu/OpenMenuContents.cs
- Gui/TabControl/Tab.cs
- Gui/TabControl/TabControl.cs
- examples/MeshViewer/MeshViewerWidget.cs
- Realize menu contents onto surface and pass to Popup
- Add support for passing separator bars to tabs
> Adjust tab styling

- Gui/TabControl/TabControl.cs
- VectorMath/Vector3.cs
- Issue MatterHackers/MCCentral#1511
Scene serialization regression after agg-sharp update
> Design tools

- MeshThumbnails/MeshThumbnails/MeshThumbnails.csproj
- MeshThumbnails/MeshThumbnails/ThumbnailTracer.cs
- OpenGlGui/TrackballTumbleWidget.cs
- VectorMath/TrackBallController.cs
- VectorMath/VectorMath.csproj
- VectorMath/WorldView.cs
- examples/MeshViewer/MeshViewerWidget.cs
- examples/RayTracerTest/RayTracerWiget.cs
- Host on MeshViewer in MatterControl
- Use directly in MeshThumbnails
- Remove MeshThumbnails Gui dependency
- Issue MatterHackers/MCCentral#1536
TrackballTumble perspective should not change after clicking Generate
> Move world transforms outs of TrackballTumbleWidget

- ImageProcessing/ExtensionMethods.cs
- MeshThumbnails/MeshThumbnails/ThumbnailEngine.cs
- MeshThumbnails/MeshThumbnails/ThumbnailTracer.cs
- Issue MatterHackers/MCCentral#1567
Thumbnail rendering mode ignored by MeshContentProvider
> Restore 1.7 AllWhite image helper, use in Orthographic mode

- DataConverters3D/MeshFaceTraceable.cs
- DataConverters3D/MeshToBVH.cs
- MeshThumbnails/MeshThumbnails/ThumbnailEngine.cs
- Issue MatterHackers/MCCentral#1592
Invalid thumbnail generation after recent updates
> Fix thumbnails regression

- GuiAutomation/AutomationRunner.cs
- Tests/Agg.Tests/Agg.UI/AutomationRunnerTests.cs
- Tests/Agg.Tests/Agg.UI/MouseInteractionTests.cs
- Tests/Agg.Tests/Agg.UI/TextEditTests.cs
- Tests/Agg.Tests/Agg/WidgetClickTests.cs
- Issue MatterHackers/MCCentral#1620
Make NameExists support a timeout
- Issue MatterHackers/MCCentral#1619
Automation ClickByName should not take a timeout value, should use sane default
> Remove timeout from ClickByName

- Gui/Themes/ActiveTheme.cs
- examples/MeshViewer/MeshViewerWidget.cs
- Initialize MaterialColor1 during construction to current color
> Remove ThemeChanged suppression via Suspend/Resume event

- RayTracer/Primitive/IBvhItem.cs
- Tests/Agg.Tests/Agg.RayTracer/TraceAPITests.cs
- agg/VertexSource/IVertexSource.cs
- agg/VertexSource/PathStorage.cs
improved IVertex source get bounds and bounds
> Improved bvh iteration

- DataConverters3D/Object3D/InteractiveScene.cs
- DataConverters3D/Object3D/Object3D.cs
- Issue MatterHackers/MCCentral#1661
MCX has invalid transforms when sliced
> Fix transform multiplication

- DataConverters3D/Object3D/InteractiveScene.cs
- DataConverters3D/Object3D/Json/IObject3DContractResolver.cs
- DataConverters3D/Object3D/Object3D.cs
- DataConverters3D/Object3D/Object3DExtensions.cs
- Issue MatterHackers/MCCentral#1721
Revise Object3D serialization
> Revise serialization

- DataConverters3D/MeshToBVH.cs
- Issue MatterHackers/MCCentral#1731
Mesh thumbnails now rendering in fixed blue color
> Fix blue thumbnails

- Csg/Solids/MeshContainer.cs
- DataConverters3D/AmfDocument.cs
- DataConverters3D/MeshFileIo.cs
- DataConverters3D/ObjSupport.cs
- DataConverters3D/Object3D/Json/IObject3DChildrenConverter.cs
- DataConverters3D/Object3D/Object3D.cs
- DataConverters3D/Object3D/Object3DExtensions.cs
- DataConverters3D/VertexSourceToMesh.cs
- PolygonMesh/Mesh.cs
- PolygonMesh/Processors/MeshHelper.cs
- PolygonMesh/Processors/StlProcessing.cs
- Tests/Agg.Tests/Agg.PolygonMesh/MeshTests.cs
- Tests/Agg.Tests/Agg.RayTracer/PolygonTraceTests.cs
- agg/agg_basics.cs
- examples/GCodeVisualizer/GCodeFileLoaded.cs
- examples/MeshViewer/MeshViewerWidget.cs
- examples/RayTracerTest/RayTracerWiget.cs
- Issue MatterHackers/MCCentral#1736
Progress reporting and task cancellation should be separated and improved
> Revise ReportProgressRatio implementation

- PolygonMesh/Face.cs
- PolygonMesh/FaceEdge.cs
- PolygonMesh/Mesh.cs
- PolygonMesh/MeshEdge.cs
- PolygonMesh/Vertex.cs
- agg/Agg.csproj
- agg/ReferenceEqualityComparer.cs
- Use expression-bodied property for ID
> Use reference equality for instance dictionary

- DataConverters3D/Object3D/Json/IObject3DChildrenConverter.cs
- Gui/FileDialogs/FileDialog.cs
- Gui/SystemWindow/SystemWindow.cs
- PlatformAbstract/ImageIO.cs
- PlatformAbstract/OsInformation.cs
- SerialPortCommunication/FrostedSerial/FrostedSerialPortFactory.cs
- agg/PluginFinder.cs
- examples/DemoRunner/DemoRunner.cs
- Add FindTypes<T> for runtime type discovery
- Rename FindAndAddPlugins to CreateInstancesOf; better convey behavior
- Remove searchDirectory option that was locked in on first call
- Issue MatterHackers/MCCentral#1735
Drag-drop delay - loading simple .mcx file takes ~5 seconds
> Convert PluginFinder to static class with generic methods

- Gui/ListBox.cs
- Gui/ScrollableWidget/ScrollBar.cs
- Issue MatterHackers/MCCentral#1780
Improve scroll container behavior, don't force reflow for scrollbars
> Add support for smaller, floating scrollbars

- Gui/GUIWidget.cs
- Gui/Menu/Menu.cs
- Gui/Menu/PopupWidget.cs
fixed popup content to use position and fixe layout bug.
> Put in a position and size on widget

- DataConverters3D/Object3D/Object3DExtensions.cs
- MatterHackers/MCCentral#1803
Settings applied to selections should persist on selection close
> Apply settings to selection on lose focus

- DataConverters3D/AmfDocument.cs
- DataConverters3D/MeshToBVH.cs
- DataConverters3D/ObjSupport.cs
- DataConverters3D/Object3D/IObject3D.cs
- DataConverters3D/Object3D/Object3D.cs
- PolygonMesh/Csg/CsgOperations.cs
> Fixing persisting types

- DataConverters3D/Object3D/InteractiveScene.cs
- PolygonMesh/Mesh.cs
> Make the selection easier to understand and more robust

- Gui/GUIWidget.cs
- Gui/TabControl/TabControl.cs
- Tests/Agg.Tests/Agg.UI/FlowLayoutTests.cs
Tabs should not change what their construction say to do in layout
> Account for fit as a constraint in shrinking stretch children

- examples/PolygonPathing/PolygonPathing.cs
Able to parse bad path data from MatterControl
Show more info about path failures
> Improved path debugging

- GuiAutomation/AutomationRunner.cs
- Issue MatterHackers/MCCentral#2045
Investigiate PulseRequiresLevelingAndLevelingWorks regression
> NamedWidgetExists should ignore SystemWindows with null PlatformWindow

- Gui/SystemWindow/SystemWindow.cs
- PlatformWin32/win32/AggGLControl.cs
- PlatformWin32/win32/OpenGLSystemWindow.cs
- PlatformWin32/win32/WinformsEventSink.cs
- PlatformWin32/win32/WinformsSystemWindow.cs
- Issue MatterHackers/MCCentral#2047
Invalid window position on test startup
> Revise Winforms startup positioning

- PlatformWin32/win32/OpenGLSystemWindow.cs
- Issue MatterHackers/MCCentral#2054
Not restoring Maximize
> Restore Maximized tracking

- Gui/SystemWindow/SystemWindow.cs
- Issue MatterHackers/MCCentral#2085
Title bar empty
> Actively assign PlatformWindow.Caption in SystemWindow.Title setter

- DataConverters3D/MeshToBVH.cs
- DataConverters3D/Object3D/IObject3D.cs
- DataConverters3D/Object3D/Object3D.cs
- DataConverters3D/Object3D/Object3DExtensions.cs
- DataConverters3D/Object3D/SafeList.cs
- MeshThumbnails/MeshThumbnails/ThumbnailEngine.cs
- MeshThumbnails/MeshThumbnails/ThumbnailTracer.cs
- examples/MeshViewer/MeshViewerWidget.cs
Made VisibleMeshes return IEnumerable<IObject3D>
Added PostUpdate to SafeList
Added World Color, OutputType & MaterialIndex
Made thumbnails use new world data
> Removed MeshRenderData

- DataConverters3D/Object3D/IObject3D.cs
- DataConverters3D/Object3D/InteractiveScene.cs
- DataConverters3D/Object3D/Json/IObject3DChildrenConverter.cs
- DataConverters3D/Object3D/Json/IObject3DContractResolver.cs
- DataConverters3D/Object3D/Object3D.cs
- DataConverters3D/Object3D/Object3DExtensions.cs
- DataConverters3D/Object3D/SafeList.cs
- PlatformWin32/win32/WinformsSystemWindow.cs
- Issue MatterHackers/MCCentral#2109
Subtract operation fails
>  Alt IObject3D.Parent

- DataConverters3D/Object3D/IObject3D.cs
- DataConverters3D/Object3D/Object3D.cs
Created an Invalidate call on IObject3D and Invalidated event on Object3D
* Please comment during review if changes seem useful.
> Made OwnerID get updated during clone

- DataConverters3D/Object3D/Object3D.cs
- PlatformWin32/win32/NativeMethods.cs
- RenderOpenGl/RenderOpenGl.csproj
- Issue MatterHackers/MCCentral#2131
If mesh changes we need to invalidate the trace data
> Invalidate trace data in Mesh assignment helper

- DataConverters3D/MeshFaceTraceable.cs
- DataConverters3D/MeshToBVH.cs
- DataConverters3D/Object3D/IObject3D.cs
- PolygonMesh/Face.cs
- PolygonMesh/Processors/FaceBspTree.cs
- PolygonMesh/Processors/MeshHelper.cs
- RayTracer/Primitive/Transform.cs
- RenderOpenGl/RenderMeshToGl.cs
- Tests/Agg.Tests/Agg.PolygonMesh/MeshTests.cs
- VectorMath/Ray.cs
- VectorMath/WorldView.cs
Ray Transform function
Improved mesh face traceable
Face AABB with matrix
> New bsp face sorting without recursion

- GuiAutomation/AutomationRunner.cs
- Tests/Agg.Tests/Agg/WidgetClickTests.cs
- Issue MatterHackers/MCCentral#2202
ClickFiresOnCorrectWidgets fails with maddening frequency
> Simplify click tests

- PlatformWin32/win32/WinformsSystemWindow.cs
- PlatformWin32/win32/WinformsSystemWindowProvider.cs
- Issue MatterHackers/MCCentral#2187
Load and Un-load filament are not closing windows correctly
> Avoid creating new PlatformWindows for visible/loaded items

- DataConverters3D/Object3D/Object3D.cs
and not recurs into children if parent has mesh
Made bounds include holes but not !Visible
> Make trace data not include non-visible meshes

- Gui/Splitter.cs
- Issue MatterHackers/MCCentral#2236
Library panel should maintain its width across application restarts
> Add DistanceChanged event, require and store ref to parent Splitter

- Tests/Agg.Tests/Agg.PolygonMesh/CsgTests.cs
- Tests/Agg.Tests/Agg.RayTracer/FrustumTests.cs
- Tests/Agg.Tests/Agg.RayTracer/PolygonTraceTests.cs
- Tests/Agg.Tests/Agg.UI/AnchorTests.cs
- Tests/Agg.Tests/Agg.UI/MouseInteractionTests.cs
- Issue MatterHackers/MCCentral#2257
Convert FixNeeded and WorkInProgress test categories into Ignore attributes
> Covert disabled test filter categories to Ignore attributes

- Gui/GUIWidget.cs
- Gui/Gui.csproj
- Gui/LayoutEngines/LayoutEngine.cs
- Gui/LayoutEngines/LayoutEngineFlow.cs
- Gui/LayoutEngines/LayoutEngineSimpleAlign.cs
- Gui/LayoutEventArgs.cs
- Gui/packages.config
- Tests/Agg.Tests/Agg.UI/AnchorTests.cs
Working on fit center test and fix
> Added a Border to guiwidget

- MeshThumbnails/MeshThumbnails/ThumbnailEngine.cs
- Issue MatterHackers/MCCentral#2279
Thumbnails not generating for Primitives
> Account for VisibleMeshes skipping Mesh on self

- DataConverters3D/ObjParser/Mtl.cs
- DataConverters3D/ObjSupport.cs
- RenderOpenGl/GLMeshTrianglePlugin.cs
Make sure we calculate face color correctly
> Don't load textures on objs when they are not on disk

- Gui/ScrollableWidget/ScrollableWidget.cs
- Gui/SystemWindow/SystemWindow.cs
Make scroll use page and arrow keys when focused
> Fixed set cursor

- DataConverters3D/Object3D/Object3D.cs
- PlatformWin32/win32/WinformsSystemWindow.cs
- Issue MatterHackers/MCCentral#2327
Color assigned per draw, color assignment creates new thread...
> Limit bsp generation to single instantiation

- Gui/GUIWidget.cs
- Gui/ScrollableWidget/ScrollableWidget.cs
Make scroll arrea consider if touch screen mode
> Make widget aware of touchscreen mode (static in GuiWidget)

- PolygonMesh/Net3dBool/Vertex.cs
issue: MatterHackers/MCCentral#2360
Change CSG mark fuction to not use recursion
> Removed the recursion

- PolygonMesh/Net3dBool/Object3D.cs
- PolygonMesh/Processors/MeshHelper.cs
- RayTracer/Primitive/Shapes/BaseShape.cs
- RayTracer/Primitive/Shapes/BoxShape.cs
- RayTracer/Primitive/Shapes/Cylinder.cs
- RayTracer/Primitive/Shapes/PlaneShape.cs
- RayTracer/Primitive/Shapes/SphereShape.cs
- RayTracer/Primitive/Shapes/TriangleShape.cs
- RayTracer/RayTracer.csproj
- RayTracer/packages.config
- VectorMath/PlaneFloat.cs
- VectorMath/TrackBallController.cs
> Improving ray tracing so we can click tumble widget

- DataConverters3D/Object3D/IObject3D.cs
- DataConverters3D/Object3D/Object3D.cs
- RenderOpenGl/RenderMeshToGl.cs
- agg/agg_basics.cs
Improve it to check for and replace numbers
add new calling method
Make sure Object3D Close does not end up modifying object in processes
Don't try to render meshes with no faces
> Unify to single GetNonCollidingName

- PolygonMesh/Csg/CsgOperations.cs
- PolygonMesh/Net3dBool/BooleanModeller.cs
- PolygonMesh/Net3dBool/Net3dBool.csproj
- agg/agg_basics.cs
> Adding some progress reporting to CSG

- DataConverters3D/MeshToBVH.cs
- DataConverters3D/Object3D/IObject3D.cs
- PolygonMesh/Face.cs
- RenderOpenGl/GL.cs
- RenderOpenGl/RenderMeshToGl.cs
- agg/Color.cs
added SetLightness function
Changed AsTriangles to IEnumerable
added AsUvTriangles
added gl convenience functions that take Vector3 and Vector2
got rid of warning for new on Object3D Parent
> added ability to render textured sorted transparent meshes

- GuiAutomation/AggInputMethods.cs
- Issue MatterHackers/MCCentral#2445
Snapshot IEnumerables in AggInputMethods to guard against
enumeration modified exceptions
> Guard against collection modified exceptions, reorder members

- DataConverters3D/AmfDocument.cs
issue: MatterHackers/MCCentral#2476
Can't ungroup hackaday from design tools calibration parts
> Improved amf loader. Can read color data and groups.

- Gui/GUIWidget.cs
- Tests/Agg.Tests/Agg.UI/AnchorTests.cs
issue: MatterHackers/MCCentral#2454
VAnchor.Center and DeviceScale cause unexpected growth
> Fixing layout bug

- Gui/Menu/DropDownList.cs
- Issue MatterHackers/MCCentral#2514
Adjust print popup menu for forced white background
> DropDownList should allow caller to specify text color

- Gui/Menu/PopupWidget.cs
- Issue MatterHackers/MCCentral#2548
Clipped library popup menu
> Constrain popup to positive X

- DataConverters3D/MeshFaceTraceable.cs
- DataConverters3D/Object3D/Object3D.cs
- DataConverters3D/Object3D/Object3DExtensions.cs
- PolygonMesh/Mesh.cs
- RayTracer/Primitive/BoundingVolumeHierarchy.cs
- RayTracer/Primitive/Difference.cs
- RayTracer/Primitive/IBvhItem.cs
- RayTracer/Primitive/Shapes/BaseShape.cs
- RayTracer/Primitive/Shapes/TriangleShape.cs
- RayTracer/Primitive/Transform.cs
- VectorMath/AxisAlignedBoundingBox.cs
Added PropertyBag to Mesh
Change BVH Contains to check a Vector3
Added an error Range to aabb contains vector3
> Made TraceData calculate more efficiently and less often

- DataConverters3D/MeshToBVH.cs
- DataConverters3D/Object3D/InteractiveScene.cs
- DataConverters3D/Object3D/Object3DExtensions.cs
- MeshThumbnails/MeshThumbnails/ThumbnailEngine.cs
- MeshThumbnails/MeshThumbnails/ThumbnailTracer.cs
- examples/MeshViewer/MeshViewerWidget.cs
issue: MatterHackers/MCCentral#2434
Fix strange offset when in sub object edit
> Improving iteration of sub edit objects (stop at described root)

- Csg/Processors/CsgToMesh.cs
- Csg/Solids/Cylinder.cs
- Csg/Solids/Round.cs
- PlatformWin32/win32/WinformsSystemWindow.cs
- PolygonMesh/Face.cs
- PolygonMesh/MeshEdge.cs
- PolygonMesh/Vertex.cs
- Tests/Agg.Tests/Agg.PolygonMesh/CsgTests.cs
- Tests/Agg.Tests/Agg.PolygonMesh/MeshTests.cs
- examples/RayTracerTest/RayTracerWiget.cs
Made CsgObject -> Mesh have option to clean
Refactoring FacesSharingMeshEdge
Made CreateCylinder take a sides
Started work on new CSG test
> Started work on new CSG test

- Gui/GUIWidget.cs
- Gui/Menu/PopupWidget.cs
> Refactor ChildrenRecursive -> Decendants

- Gui/Menu/PopupWidget.cs
- Issue MatterHackers/MCCentral#2588
Menu should be right aligned
> Fix align right, add support for auto align in x when clipped

- Gui/GUIWidget.cs
- Gui/Menu/PopupWidget.cs
Issue: MatterHackers/MCCentral#2638
Reconsider Descendants(bool includeThis = true)
> Wrote DescendantsAndSelf

- RenderOpenGl/OverhangeRender.cs
- RenderOpenGl/RenderMeshToGl.cs
- RenderOpenGl/RenderOpenGl.csproj
Recomputes when needed
Caches values
issue: MatterHackers/MCCentral#2287
New objects dragged into scene do not get Overhang rendering mode
> Wrote an overhang renderer class

- Gui/Keyboard.cs
issue: MatterHackers/MCCentral#2494
No way to drag/pan without middle click?
> Make sure we set control and shift correctly in Keyboard

- DataConverters3D/MeshToBVH.cs
- MeshThumbnails/MeshThumbnails/ThumbnailTracer.cs
issue: MatterHackers/MCCentral#2316
Bad thumbnails for some models
> Fixed thumbnail rendering for mcx files

- DataConverters3D/MeshFileIo.cs
- examples/MeshViewer/MeshViewerApplication.cs
- Issue MatterHackers/MCCentral#2527
Too many authorities on valid files types
> Remove file extension definitions

- Gui/Menu/PopupWidget.cs
- Gui/ScrollableWidget/ScrollableWidget.cs
- GuiAutomation/AutomationRunner.cs
Made popup widget get the right scroll
Made automation runner able to find widgets that aren't visible
> Added scroll into view

- DataConverters3D/AmfDocument.cs
- DataConverters3D/MeshFileIo.cs
- DataConverters3D/ObjSupport.cs
- DataConverters3D/Object3D/Object3D.cs
- DataConverters3D/VertexSourceToMesh.cs
- PlatformWin32/win32/AggGLControl.cs
- PolygonMesh/Mesh.cs
- PolygonMesh/Processors/StlProcessing.cs
- Tests/Agg.Tests/Agg.PolygonMesh/MeshTests.cs
- Issue MatterHackers/MCCentral#2639
Zero byte plating file hangs startup
> Set GLControl preferred options to improve quality

- MarchingSquares/MarchingSquaresByte.cs
- Issue MatterHackers/MCCentral#2582
Image converter - Image outline not aligned with model correctly
> Account for one pixel image expansion

- DataConverters3D/AmfDocument.cs
- DataConverters3D/MeshFileIo.cs
- DataConverters3D/ObjSupport.cs
- PolygonMesh/Mesh.cs
- PolygonMesh/Processors/StlProcessing.cs
> Take out default mesh CleanAnd Merge from loading

- DataConverters3D/DataConverters3D.csproj
- DataConverters3D/Object3D/IObject3D.cs
- DataConverters3D/Object3D/InteractiveScene.cs
- DataConverters3D/Object3D/Object3D.cs
- DataConverters3D/Object3D/Object3DExtensions.cs
- Localizations/TranslationMap.cs
> Adding Remove and Bake to IObject3D

- DataConverters3D/Object3D/Object3D.cs
- Issue MatterHackers/MCCentral#2819
Discuss this locking behavior
> Only clear tracking variable if we own it

- DataConverters3D/Object3D/Object3D.cs
issue: MatterHackers/MCCentral#2838
AutomaticallyCleanAndMerge serializes into MCX
> Took out AutomaticallyCleanAndMerge as it was not used

- DataConverters3D/Object3D/Object3D.cs
> Make default bake not call the virtual remove

- RenderOpenGl/Renderer/RendererOpenGL.cs
- agg/Color.cs
- agg/Graphics2D.cs
- agg/Image/ImageGraphics2D.cs
> Made it possible to get the width and height of a graphics 2d

- DataConverters3D/MeshFileIo.cs
- DataConverters3D/VertexSourceToMesh.cs
- PolygonMesh/Processors/MeshHelper.cs
- VectorMath/MathHelper.cs
Improved GetDeltaAngle
Created copy faces function
> Made revolve create the start and end face when required

- RenderOpenGl/RenderMeshToGl.cs
- agg/Image/ImageBuffer.cs
issue: MatterHackers/MCCentral#2878
Textures should check for transparency
> Ability to set and check if an ImageBuffer has transparency

- DataConverters3D/Object3D/Object3D.cs
issue: MatterHackers/MCCentral#2885
Setting selection color should invalidate scene
> Make sure we invalidate on color changes

- DataConverters3D/Object3D/IObject3D.cs
- DataConverters3D/Object3D/InteractiveScene.cs
- DataConverters3D/Object3D/Object3D.cs
- PolygonMesh/MIConvexHull.xml
- PolygonMesh/Mesh.cs
- PolygonMesh/PolygonMesh.csproj
- PolygonMesh/TransformedAabbCache.cs
- PolygonMesh/packages.config
Added MIConvexHull nuget
Fixed a bug in copying non-cleaned meshes
Make it possible to turn off drawing selection
> Improved calculation of mesh bounds

- DataConverters3D/DataConverters3D.csproj
- DataConverters3D/MeshFileIo.cs
- DataConverters3D/Object3D/AssetObject3D.cs
- DataConverters3D/Object3D/Object3D.cs
- DataConverters3D/Object3D/Object3DExtensions.cs
- MeshThumbnails/MeshThumbnails/MeshThumbnails.csproj
- Issue MatterHackers/MCCentral#2879
Ensure consistency and consolidate all sha1 helpers
> Revise Assets

- DataConverters3D/VertexSourceToMesh.cs
- Gui/Keyboard.cs
- PlatformWin32/win32/WinformsEventSink.cs
Improved keyboard input after focus (clear down keys)
> Improved revolve

- MarchingSquares/MarchingSquaresByte.cs
- agg/VertexSource/IVertexSource.cs
> Added IVertexSource get weighted center

- Gui/Gui.csproj
- Gui/ResponsiveImageWidget.cs
- RenderOpenGl/Renderer/RendererOpenGL.cs
part of: MatterHackers/MCCentral#2888
Restore + page banner
> Making a new Responsive scaling ImageWidget

- DataConverters3D/Object3D/IObject3D.cs
- DataConverters3D/Object3D/InteractiveScene.cs
- DataConverters3D/Object3D/Object3D.cs
issue: MatterHackers/MCCentral#2927
Remove IObject3D.ActiveEditor
> Took out active editor property

- Gui/ImageSequenceWidget.cs
- Gui/SystemWindow/ToolTipManager.cs
- Gui/UiThread.cs
- OpenGlGui/TrackballTumbleWidget.cs
issue: MatterHackers/MCCentral#2961
Add SetInterval type method to UiThread
> Added SetInterval to uithread

- DataConverters3D/Object3D/AssetObject3D.cs
- DataConverters3D/Object3D/Object3D.cs
- Localizations/TranslationMap.cs
- agg/Platform/Providers/IStaticData.cs
MatterHackers/MCCentral#2946
StaticData.MapPath should be deprecated and removed
> Remove MapPath

- DataConverters3D/VertexSourceToMesh.cs
- PolygonMesh/Net3dBool/CsgObject3D.cs
- PolygonMesh/Net3dBool/Vertex.cs
Faster clasification of vertexes
> Fixed seam on revolve

- Gui/Menu/PopupWidget.cs
- Issue MatterHackers/MCCentral#3019
PopupButtons fail to popup when MakeScrollable is false
> Clamp height to MaxHeight, otherwise content height

- DataConverters3D/Object3D/IObject3D.cs
- DataConverters3D/Object3D/InteractiveScene.cs
- DataConverters3D/Object3D/Object3D.cs
issue: MatterHackers/MCCentral#2950
Improve Bake words and icon
> Changed Bake to MakePermanent

- Gui/TextWidgets/TextWidget.cs
- Issue MatterHackers/MCCentral#3092
Illegible disabled radio items
> Remove DisabledColor property, calc disabledColor on TextColor set

- Gaming/Game/GamePlatform.cs
- Gui/Animation.cs
- Gui/ImageSequenceWidget.cs
- Gui/SystemWindow/ToolTipManager.cs
- Gui/UiThread.cs
- OpenGlGui/TrackballTumbleWidget.cs
- agg/agg_basics.cs
Added EaseIn EaseOut and EaseInOut to agg_basics
> Made UiThread SetInterval return a RunningInterval

- Gui/GUIWidget.cs
- agg/Platform/Providers/IStaticData.cs
- Issue MatterHackers/MCCentral#3116
Inconsistent border strengths
> Draw borders outside of child loop

- Gui/GUIWidget.cs
- Gui/LayoutEngines/LayoutEngineFlow.cs
- Gui/LayoutEngines/LayoutEngineSimpleAlign.cs
issue: MatterHackers/MCCentral#3011
Like margin, border should be outside of client area
> Moving border outside the client area

- Gui/GUIWidget.cs
- Issue MatterHackers/MCCentral#3129
Missing top borders
> Revise DrawBorder to address issues in #3129

- Gui/Menu/DropDownList.cs
- Issue MatterHackers/MCCentral#3126
> Remove dropdown list border workaround

- OpenGlGui/TrackballTumbleWidget.cs
- VectorMath/TrackBallController.cs
- VectorMath/WorldView.cs
The vanishing point can be moved in x
issue: MatterHackers/MCCentral#3130
change the rotation center of the 3d view to be the center of the visible window (non-inclusive of selection bar)
> Got the view to be off center

- Gui/GUIWidget.cs
- Issue MatterHackers/MCCentral#3171
Something got messed up with baby stepping on this print
> Add InvokeClick to GuiWidget

- Gui/Menu/DropDownList.cs
- Issue MatterHackers/MCCentral#3183
Fix icon margins in droplist control
> Improve dropdownlist icon positioning for simpler caller control

- DataConverters3D/Object3D/Object3D.cs
issue: MatterHackers/MCCentral#3213
Can't copy the ImageCoin throws an exception
> Only set the mesh if it changed (often null == null)

- DataConverters3D/Object3D/Object3D.cs
- agg/Color.cs
Added named colors to a static in Object3D
> Improved color operations

- Gui/ImageSequenceWidget.cs
- PlatformWin32/win32/FileSystemStaticData.cs
- agg/Image/ImageSequence.cs
issue: MatterHackers/MatterControl#3253
Put in gif sub frame timing
> Get the frame times out of the gif

- Gui/Clipboard/Clipboard.cs
- Gui/Clipboard/ISystemClipboard.cs
- Gui/TextWidgets/InternalTextEditWidget.cs
- GuiAutomation/AggInputMethods.cs
- GuiAutomation/AutomationRunner.cs
- PlatformWin32/win32/WindowsFormsClipboard.cs
- Tests/Agg.Tests/Agg.UI/FlowLayoutTests.cs
- Tests/Agg.Tests/Agg.UI/MenuTests.cs
- Tests/Agg.Tests/Agg.UI/MouseInteractionTests.cs
- Tests/Agg.Tests/Agg.UI/TextEditTests.cs
Got agg input methods working better
Working on adding past image to clipboard
Working on adding past FileDropList to clipboard
issue: MatterHackers/MCCentral#2755
Add support for and migrate to AggInputMethods in agg tests
> Automation runner defaults to agg input methods and tests pass

- Tests/Agg.Tests/Agg.Tests.csproj
- Tests/Agg.Tests/Agg.UI/BorderTests.cs
- Issue MatterHackers/MCCentral#3184
Complete border validation tests
> Add border validation tools

- Gui/GUIWidget.cs
- PlatformWin32/PlatformWin32.csproj
- PlatformWin32/win32/WinformsInformationProvider.cs
- agg/Platform/AggContext.cs
- agg/Platform/Providers/IOsInformationProvider.cs
also issue: MatterHackers/MCCentral#3253
Inconsistent border stroke
> Added the ability to get physical memory

- Gui/Animation.cs
- Gui/ImageSequenceWidget.cs
- agg/Image/ImageSequence.cs
issue: MatterHackers/MCCentral#3298
Don't invalidate animation unless we change a frame
> improving animation playback

- GuiAutomation/AggInputMethods.cs
issue: MatterHackers/MCCentral#3293
Investigate failing DoUndo tests
> Make sure on a cntrl A we set the controls key correctly

- Gui/ImageSequenceWidget.cs
- PlatformWin32/win32/FileSystemStaticData.cs
- agg/Image/ImageSequence.cs
Refactoring
issue: MatterHackers/MCCentral#3296
Loading animation for help gifs freezes after load and before final show
> Added Copy to ImageSequence

- DataConverters3D/ObjSupport.cs
- Gui/Menu/PopupWidget.cs
- PlatformWin32/win32/WinformFileDialogProvider.cs
- Issue MatterHackers/MatterControl#3311
Extruder control window doesn't disappear after changing filament type
> Restore focus after child popup close

- Gui/GUIWidget.cs
- Gui/Gui.csproj
- Gui/TreeView/TreeNode.cs
- Gui/TreeView/TreeView.cs
- agg/Font/TypeFace.cs
> Working on new tree view

- Gui/TreeView/TreeNode.cs
- Gui/TreeView/TreeView.cs
- RenderOpenGl/Renderer/RendererOpenGL.cs
- agg/VertexSource/Arc.cs
issue: MatterHackers/MCCentral#3385
Lost Blue circles on x and y axis rotate controls
issue: MatterHackers/MCCentral#3386
lost snapping triangles on rotate z control
> fixing rotation circles

- DataConverters3D/Object3D/IObject3D.cs
- DataConverters3D/Object3D/InteractiveScene.cs
- DataConverters3D/Object3D/Object3D.cs
- DataConverters3D/Object3D/UndoCommands/ReplaceCommand.cs
- Gui/GUIWidget.cs
- PolygonMesh/Mesh.cs
- RenderOpenGl/GL.cs
adding rebuild and rebuilding to IObject3D
> Mesh threading improvements

- DataConverters3D/Object3D/Object3D.cs
- PolygonMesh/Mesh.cs
- PolygonMesh/Processors/MeshHelper.cs
- PolygonMesh/VertexCollection.cs
- VectorMath/Vector3.cs
Don't clear re-building in objec3d clean mesh if we did not set it
Faster Lerp when 0 or 1
refactoring
> Improved mesh copy to always go fast and fixed bugs

- PolygonMesh/Mesh.cs
- Tests/Agg.Tests/Agg.PolygonMesh/MeshTests.cs
> Add created mesh edge to mesh edge list on split

- DataConverters3D/AmfDocument.cs
- DataConverters3D/MeshFileIo.cs
- DataConverters3D/MeshToBVH.cs
- DataConverters3D/Object3D/IObject3D.cs
- DataConverters3D/Object3D/InteractiveScene.cs
- DataConverters3D/Object3D/Object3D.cs
- DataConverters3D/Object3D/Object3DExtensions.cs
- MeshThumbnails/MeshThumbnails/ThumbnailEngine.cs
- examples/MeshViewer/MeshViewerWidget.cs
Made visible meshes return only the object not the object and mesh (mesh is on object)
Put in some debugging
> Changing Rebuilding to Susspend and Resume rebuilding

- Gui/Menu/DropDownList.cs
- Issue MatterHackers/MCCentral#2032
Invalid serial port state
> Non-match should set SelectedIndex to -1

- DataConverters3D/Object3D/InteractiveScene.cs
- Issue MatterHackers/MCCentral#3500
Drag select around a single item now results in a selection group rather
than single selection item
> Fix selection regressions

- DataConverters3D/DataConverters3D.csproj
- DataConverters3D/Object3D/ChildrenSelector.cs
- DataConverters3D/Object3D/IObject3D.cs
- DataConverters3D/Object3D/Object3D.cs
- Gui/ImageWidget.cs
Took out hole output type
part of issue: MatterHackers/MCCentral#3456
Second subtract creates bad data
> Added child selector and object3d clone keeps it updated

- PolygonMesh/Mesh.cs
issue: MatterHackers/MCCentral#3505
Mirror generating bad back faces
> Fixing reverse meshes

- Gui/RadioButton/RadioButtonViewText.cs
- Issue MatterHackers/MCCentral#3512
Use theme colors
> Add and use virtual TextColor

- DataConverters3D/Object3D/ChildrenSelector.cs
- DataConverters3D/Object3D/IObject3D.cs
- DataConverters3D/Object3D/Object3D.cs
> Took out object list attribute

- Gui/FLowLeftRightWithWrapping.cs
issue: MatterHackers/MCCentral#3597
Exception on load after Start page revisions
> Make sure we access parent in a recursive / thread safe way

- DataConverters3D/Object3D/IObject3D.cs
- PolygonMesh/Face.cs
- PolygonMesh/Vertex.cs
- agg/Color.cs
Estimated memory size for mesh
Mesh Render Id
Get long hash for color
default constructor for face and vertex
> Created the data to allow thumbnails to be cached by mesh id

- DataConverters3D/Object3D/IObject3D.cs
- PolygonMesh/Mesh.cs
Use this when getting the IObject3D MeshRenderId
> Maintain a Mesh hash code before clean

- DataConverters3D/Object3D/InteractiveScene.cs
- Gui/TextWidgets/TextWidget.cs
- Gui/TextWidgets/UndoBuffer.cs
- PolygonMesh/Mesh.cs
add finalizer to mesh
Make setting bold do expand if needed
issue: MatterHackers/MCCentral#3712
Limit undo buffer count to ~10
> Limit undos to 10

- Gui/Button/Button.cs
- Gui/DiagnosticsWidget.cs
- Gui/FLowLeftRightWithWrapping.cs
- Gui/GUIWidget.cs
- Gui/LayoutEngines/LayoutEngineFlow.cs
- Gui/LayoutEngines/LayoutEngineSimpleAlign.cs
- Gui/RadioButton/RadioButton.cs
- Gui/RadioButton/RadioButtonViewStates.cs
- examples/GUITester/Pages/TestAnchorTests.cs
Spend up GlowLeftRightWithWrapping
part of issue: MatterHackers/MCCentral#3722
Make text wrapping work in mark down
> Changed SuspendLayout() -> using(LayoutLock())

- DataConverters3D/Object3D/Object3D.cs
- PolygonMesh/Mesh.cs
- PolygonMesh/VertexCollection.cs
Made Sort always do the work requested
> Refactoring IsSorted to Sorted

- PlatformWin32/win32/WinformsSystemWindow.cs
- Issue MatterHackers/MCCentral#3802
Remove unused Win32 touch implementation form Winforms base
> Remove unused code

- DataConverters3D/Object3D/Object3D.cs
- VectorMath/Matrix4x4.cs
> Working in rotate

- PolygonMesh/Mesh.cs
- PolygonMesh/PolygonMesh.csproj
issue: MatterHackers/MCCentral#3827
Make ungroup a long running task
> Put in copy progress reporting

- Gui/FLowLeftRightWithWrapping.cs
- Gui/Gui.csproj
- Gui/ImageSequenceWidgetResponsive.cs
- Gui/ImageWidgetResponsive.cs
Making wrapping work with new responsive widget
> Creating a ImageSequenceWidgetResponsive

- DataConverters3D/Object3D/InteractiveScene.cs
- examples/MeshViewer/MeshViewerWidget.cs
issue: MatterHackers/MCCentral#3556
Remove deprecated Scene.HasSelection property
> Removed HasSelection

- agg/Agg.csproj
- agg/Image/ImageBuffer.cs
- agg/Image/ThresholdFunctions/AlphaThresholdFunction.cs
- agg/Image/ThresholdFunctions/HueThresholdFunction.cs
- agg/Image/ThresholdFunctions/IThresholdFunction.cs
- agg/Image/ThresholdFunctions/MapOnMaxIntensity.cs
- agg/Image/ThresholdFunctions/SilhouetteThresholdFunction.cs
- agg/VertexSource/IVertexSource.cs
moving threshold functions to agg
> Working to get weighted centering available on image

- GuiAutomation/AutomationRunner.cs
- Issue MatterHackers/MCCentral#3908
Investigate failing CloseShouldNotStopSDPrint
> Move mouse to widget, with consideration for current position

- Gui/ScrollableWidget/ScrollableWidget.cs
issue: MatterHackers/MCCentral#3923
Help (markdown widget) scrolls way to slow
> Doubled our default scroll speed

- agg/PluginFinder.cs
- Issue MatterHackers/MCCentral#3911
> Drop support for plugins within exe files

- DataConverters3D/Object3D/AssetObject3D.cs
- DataConverters3D/Object3D/Object3D.cs
- DataConverters3D/Object3D/Object3DExtensions.cs
- Issue MatterHackers/MatterControl#3573
Slice error
> Add FileMissingMesh, use for failed loads, skip persist if assigned

- GuiAutomation/AggInputMethods.cs
- PlatformWin32/win32/WinformsSystemWindow.cs
issue: MatterHackers/MCCentral#4029
During load filament window X (close) does not turn off heat like cancel does
> Make sure we let agg know if a system window has been closed by the os

- Gaming/Game/GamePlatform.cs
- Gui/CheckBox/CheckBoxViewSates.cs
- Gui/DiagnosticsWidget.cs
- Gui/GUIWidget.cs
- Gui/ImageWidget.cs
- Gui/Menu/Menu.cs
- Gui/Menu/PopupWidget.cs
- Gui/SystemWindow/SystemWindow.cs
- Gui/TabControl/Tab.cs
- Gui/TextWidgets/TextEditWidget.cs
- Gui/WidgetClosingEnventArgs.cs
- GuiAutomation/AggInputMethods.cs
- GuiAutomation/AutomationRunner.cs
- PlatformWin32/win32/WinformsSystemWindow.cs
- examples/GUITester/Pages/WebCamPage.cs
changing CloseEventArgs to EventArgs
> Changing close to not take any params

- GuiAutomation/AggInputMethods.cs
- GuiAutomation/AutomationRunner.cs
- GuiAutomation/GuiAutomation.csproj
- GuiAutomation/MouseConsts.cs
- GuiAutomation/app.config
- PlatformWin32/PlatformWin32.csproj
- PlatformWin32/win32/NativeMethods.cs
- PlatformWin32/win32/WindowsInputMethods.cs
- Veldrid/RenderOpenGL/VeldridGL.cs
> Changing automation runner to .netstandard

- Gui/GUIWidget.cs
- Issue MatterHackers/MCCentral#4109
Descendants is not DepthFirst?
> Revise Descendants for depth-first search

- DataConverters3D/Object3D/IObject3D.cs
- DataConverters3D/Object3D/Object3D.cs
add copy properties to IObject3D overrides
> Make sure base apply makes a group

- Gui/Menu/DropDownList.cs
- Gui/Menu/Menu.cs
- Gui/Menu/PopupWidget.cs
Improve our searching for SystemWindow
issue: MatterHackers/MCCentral#4181
Cannot change thumbnail style
> Don't close if opening a dropDown list on a popup widget

- Gui/WindowWidget/TitleBarWidget.cs
- Gui/WindowWidget/WindowWidget.cs
> Cleaned up border to not affect expected rendering

- Gui/Menu/PopupWidget.cs
issue: MatterHackers/MCCentral#4242
Menu close regression
> fixing menu close problem

- Gui/Splitter.cs
- Issue MatterHackers/MCCentral#4301
Unable to set top border on Splitter.Panel1
> Update splitter with int constraints and border consideration

- Gui/ImageWidget.cs
- Gui/ResponsiveImageWidget.cs
- Issue MatterHackers/MCCentral#4585
Memory leak in ImageWidget when source image is static
> Revise ImageChanged listeners

- DataConverters2D/VertexSourceToTesselator.cs
- Gui/GUIWidget.cs
- agg/VertexSource/ConnectedPaths.cs
- agg/VertexSource/RoundedRect.cs
Add TransformFromParentSpace for rectangles
> Improving the ability to create complex paths

- Gui/UiThread.cs
- PlatformWin32/win32/WinformsSystemWindow.cs
- Issue MatterHackers/MCCentral#4556
Make Linux alpha build
> Always set processingOnIdle false when completed

- Typography.OpenFont/IGlyphTranslator.cs
this resolve
https://github.com/MatterHackers/MatterControl/issues/4066#issuecomment-445269796
> fixing ttf glyph translator

- PlatformWin32/win32/WinformsSystemWindow.cs
- Issue MatterHackers/MCCentral#4701
Many automation tests failing due to single window mode changes
> Revised specialized shutdown case for "RootSystemWindow"

- Gui/GUIWidget.cs
This reverts commit d9c772a3bd7ffc7839004cb33a67fe189f4b9ac7.
> Revert "Make screen space be the topmost window"

- PlatformWin32/win32/WinformsEventSink.cs
- Issue MatterHackers/MCCentral#4798
Add support for drag drop image url
> Add html and text drag data as paths with leading markers

- PolygonMesh/Csg/SliceLayer.cs
- PolygonMesh/Net3dBool/CsgFace.cs
- PolygonMesh/Net3dBool/Line.cs
- PolygonMesh/Processors/MeshHelper.cs
- RayTracer/Primitive/Shapes/Cylinder.cs
- RayTracer/Primitive/Shapes/PlaneShape.cs
- Tests/Agg.Tests/Agg.VectorMath/VectorMathTests.cs
- VectorMath/Frustum.cs
- VectorMath/Plane.cs
> Fixing texturing on simple mesh

- PolygonMesh/PolygonMesh.csproj
- PolygonMesh/Processors/MeshConvexHull.cs
- VectorMath/AxisAlignedBoundingBox.cs
- VectorMath/Vector2.cs
- VectorMath/Vector3.cs
- VectorMath/Vector3Float.cs
- VectorMath/Vector4.cs
Make sure CreatHulMesh does not crash on 0 size meshes
Upgraded MIConvexHull
> Improved GetLongHashCode for vectors

- DataConverters3D/VertexSourceToMesh.cs
- PolygonMesh/Mesh.cs
- PolygonMesh/MeshEdge.cs
- RenderOpenGl/GLMeshWirePlugin.cs
Added function to get VertexFaceList
Added a clean and merge mesh function
> Added a mesh edge class and function to get a list of them

- PolygonMesh/Mesh.cs
issue: MatterHackers/MCCentral#4873
validate mirror on y filpping
> Better treatment of face normal while transforming

- PolygonMesh/Mesh.cs
- VectorMath/Vector3.cs
- VectorMath/Vector3Float.cs
- VectorMath/Vector4.cs
- agg/Image/ImageBuffer.cs
attempting to get better long hash code for mesh
don't use ref for Vector4 Transform
> sped up HasTransparency

- Gui/Menu/PopupWidget.cs
- Issue MatterHackers/MCCentral#4893
DropLists fail to popup after fixes for #4775
> Use topmost SystemWindow

- GuiAutomation/AggInputMethods.cs
- Find the top systemWindow, then find its root
> Send key events to the root of the top SystemWindow

- DataConverters3D/Object3D/InteractiveScene.cs
- PolygonMesh/Csg/CsgOperations.cs
Gets the selection logic to be easy to add to many operations
> Created new selection maintainer

- DataConverters3D/Object3D/IObject3D.cs
- DataConverters3D/Object3D/Object3D.cs
- DataConverters3D/Object3D/UndoCommands/ReplaceCommand.cs
remove undo buffer from invalidate type
> Change the Invalidate Type to flags

- DataConverters3D/Object3D/Object3DExtensions.cs
- DataConverters3D/Object3D/UndoCommands/ReplaceCommand.cs
Fixed replace command to work with new method
> Added extension methods to work on IEnumerable<IObject>

- DataConverters3D/Object3D/IObject3D.cs
This tells us the editor display is invalid but not the object
> Make an invalidate type for DisplayValues

- agg/VertexSource/VertexStorage.cs
- Issue MatterHackers/MCCentral#4936
Parsed Svg path incorrect
> Implement smooth/curveto Bézier command with reflected control point

- VectorMath/Matrix4x4.cs
- VectorMath/Vector2.cs
- VectorMath/Vector3.cs
- VectorMath/Vector4.cs
This checks for NaN and Infinity being present in the data
> Add the ability to check for isvalid on Vector Math types

- DataConverters3D/Object3D/Object3D.cs
issue: MatterHackers/MCCentral#3989
Consider excluding support from layflat
> Add function to get aabb with consideration of child decent

- PlatformWin32/win32/ImageIOWindowsPlugin.cs
attempted to add support for multiple writes by having a slightly more intelligent lock
than just a single lock
this seems to completely fix this issue with web thumbnails sometimes not
getting every picture
issue:
MatterHackers/MCCentral#5286
New WebCache system throws lots of generic error in GDI+ on startup
> Put in a thread lock so we don't have overlapped writes to the same file

- PlatformWin32/win32/WinformsSystemWindow.cs
- Issue MatterHackers/MatterControl#4258
Incomplete redraw after filament runout error
> Restore window if client code calls ShowSystemWindow

- RenderOpenGl/ImageGlPlugin.cs
- Issue MatterHackers/MCCentral#5390
Recent item thumbnails rarely displayed
> Add method to purge OpenGL texture cache

- PolygonMesh/FaceList.cs
- PolygonMesh/Mesh.cs
> After re-calculate normals do a mark as changed

- Gui/GUIWidget.cs
- Issue MatterHackers/MCCentral#5508
Tab key fails to advance focus
> Exclude disabled widgets from TabStops list

- PolygonMesh/Face.cs
- PolygonMesh/Mesh.cs
issue: MatterHackers/MCCentral#5526
Incorrect face normals for twisted mesh
> Fixing calculate normal

- RayTracer/Primitive/Shapes/PlaneShape.cs
- agg/VertexSource/ReversePath.cs
- agg/VertexSource/VertexStorage.cs
- Issue MatterHackers/MCCentral#5563
VertexStorage serialization closes open paths
> Conditional Close path

- Gui/CheckBox/CheckBox.cs
- Gui/GUIWidget.cs
- Gui/Menu/Menu.cs
- Gui/ResponsiveImageSequenceWidget.cs
- Gui/ResponsiveImageWidget.cs
- Issue MatterHackers/MCCentral#3445
Change accessibility of OnClick to protected, revise callers to use
InvokeClick()
> Change OnClick to protected

- PolygonMesh/Mesh.cs
- PolygonMesh/Processors/MeshConvexHull.cs
Adding function to get the area of a polygon face
> Fixing errors in creating convex hull

- PolygonMesh/Mesh.cs
tumble cube in MC showed this error
> fixing face texturing

- Gui/TextWidgets/InternalTextEditWidget.cs
- PlatformWin32/win32/ImageIOWindowsPlugin.cs
- PlatformWin32/win32/WinformsEventSink.cs
- PlatformWin32/win32/WinformsSystemWindow.cs
- agg-sharp.sln
- agg/Graphics2D.cs
- agg/Image/ImageBuffer.cs
- agg/Image/ImageGraphics2D.cs
Put in new render scale with clipping
Fixed issue with text widget getting bad index
Make converting Bitmap to Image public
Select the last widget on focus window
> Made image cropping take a filter function

- Gui/TextWidgets/TextWidget.cs
- Typography.OpenFont/Tables/Post.cs
- Typography.OpenFont/Typeface.cs
- agg/Font/TextWrapping.cs
- agg/Font/TypeFace.cs
- agg/Font/TypeFacePrinter.cs
- agg/Platform/AggContext.cs
> Improving font debugging render

- Gui/CheckBox/CheckBoxViewText.cs
issue: https://github.com/MatterHackers/MCCentral/issues/6130
> Fix crash on draw

- DataConverters3D/Object3D/Object3D.cs
- Glfw/GlfwPlatformWindow.cs
- PlatformWin32/win32/FileSystemStaticData.cs
- RenderOpenGl/RenderMeshToGl.cs
issue: MatterHackers/MatterControl#4818
Loading from save has corrupted width for cubes with color change
> Make sure we lock Objects3D while desterilizing

- Gui/TextWidgets/InternalTextEditWidget.cs
- Tests/Agg.Tests/Agg.UI/TextEditTests.cs
Here is my proposal to resolve MatterHackers/MatterControl#1411.
> Add ability to select text with Shift + Click in TextEditWidget

- Glfw/GlfwPlatformWindow.cs
- Gui/Keyboard.cs
- GuiAutomation/AggInputMethods.cs
- GuiAutomation/AutomationRunner.cs
- PlatformWin32/win32/NativeMethods.cs
- PlatformWin32/win32/OpenGLSystemWindow.cs
- PlatformWin32/win32/WindowsInputMethods.cs
- PlatformWin32/win32/WinformsSystemWindow.cs
This should be matched with a pull request for MatterHackers/MatterControl#5188.
> Extend automation plumbing to support clicking with modifiers

- Gui/Animation.cs
Stick a sleep after `update(updates)`, and `animation.Dispose()` will get called before returning.
Wait for the update handler to stop itself instead.
> Fix race condition in UI animation.

- Gui/Animation.cs
- VectorMath/AxisAlignedBoundingBox.cs
MatterControl PR got:
> AxisAlignedBoundingBox.cs(40,85): error CS8107: Feature 'default literal' is not available in C# 7.0. Please use language version 7.1 or greater.
The PR: https://github.com/MatterHackers/MatterControl/pull/5253
> Change to satisfy MatterControl appveyor build.

- Gui/Animation.cs
- RenderOpenGl/WorldViewExtensions.cs
- VectorMath/AxisAlignedBoundingBox.cs
Appveyor accepts this version in the MatterControl PR.
> Should be the final change to satisfy appveyor.

- Gui/FlowLeftRightWithWrapping.cs
Support for minimum content width logic in MC, irrespective of flow or position
> Add property for child content width
