MatterHackers/agg-sharp

SerialPortCommunication/FrostedSerial/FrostedSerialPortFactory.cs
SerialPortCommunication/SerialHelper/build.sh

Ensure libSetSerial.so is compiled for x86 and only call set_baud workaround on Linux when needed. To build on Linux you likely need to add libc6-dev-i386 ala:
sudo apt-get install libc6-dev-i386

Limit Linux baud workaround to rates above 115200

---

Gui/SoftKeyboard.cs

- Switch hadFocusWidget back to instance member
- Duplicate ContentOffsets would null static member losing IsActive state
- Fixes #106321662
The MoveContentBackDown function was testing if it should lower the keyboard by checking hadFocusWidget for null. I wasn't aware multiple ContentOffset controls would be active at the same time and the effect was that the first one nulled the static hadFocusWidget variable and the second one would test for and consider the keyboard already lowered.

Change SoftKeyboard.IsActive to manually set property

---

Gui/GUIWidget.cs
PlatformWin32/win32/WindowsFormsAbstract.cs

- Fire OnClosing during GuiWidget.Close
- Run OnClosing on the first child of WindowsFormsAbstract rather than directly on itself
- Rename CloseAndRemoveAllChildren to CloseAllChildren to better convey its behavior

Call OnClosing when closing GuiWidgets

---

DataConverters3D/AmfDocument.cs
DataConverters3D/DataConverters3D.csproj
DataConverters3D/MeshFileIo.cs
DataConverters3D/Object3D/IObject3D.cs
DataConverters3D/Object3D/Object3D.cs
DataConverters3D/Object3D/Object3DExtensions.cs
PolygonMesh/Processors/StlProcessing.cs
examples/MeshViewer/MeshViewerWidget.cs

- Add IObject3D.Flatten to reduce a graph into a MeshGroup
- New Amf loader (AmfDocument) to replace AmfProcessing
- SetMeshAfterLoad merged into LoadMesh
- Cached mesh data now done at IObject3D level instead of MeshGroups

Revise MeshIo to return IObject3D graphs

---

DataConverters3D/Object3D/Object3DExtensions.cs

- Fixes drag issues with all instances pointing to a single reference

IObject3D cache hits must be cloned rather than referenced

---

Gui/TabControl/Tab.cs
Gui/TabControl/TabBar.cs
Gui/TabControl/TabControl.cs

- Issue MatterHackers/MatterControl#986
- Use auto properties
- Rename TabePageControlledByTab to TabPage
- Remove excess TabPage setter (SwitchToPage)
- Use Collection.Index of for SelectedIndex

Refactor tab control, remove exceptions when requested pages missing

---

examples/GCodeVisualizer/Renderer/RenderFeatures/RenderFeatureExtrusion.cs

They are likely to have truncation errors due to the resolution of the slicer.

Don't change the extruder width for very small lines.

---

WindowsFileDialogs/FileDialogPlugin.cs
examples/GCodeVisualizer/GCodeFileLoaded.cs

We use the filename is not null as a trigger to save.

Make sure clicking cancel in save dialog results in no file name.

---

Gui/GUIWidget.cs
Gui/TabControl/Tab.cs
Gui/TabControl/TabBar.cs
Gui/TabControl/TabControl.cs
Gui/TabControl/TabPage.cs
agg/agg_color_rgba.cs

- Make GuiWidget.Visible virtual
- Switch Transparent color to low RGB, high alpha
- Use AutoProperty for Tab.TabPage
- Remove exceptions on property accessors
- Rename TabPageArea to TabPageContainer
- Remove TabPageCollection type
- Remove UI. prefix
- Don't automatically select the first tab for efficiency
- On first draw, select the TabPage[0] if nothing is selected
- Remove dead code
- Proxy TabCount and SelectTabName to child objects
- Add LazyTab type
- Defer widget construction to when first made visible
- Issue MatterHackers/MCCentral#536

Add LazyTabs for Touchscreen view

---

Tests/Agg.Tests/Agg.UI/AutomationTesterHarness.cs

- Frees blocking thread for cleaner shutdown

Use async WhenAny for code-under-test timeout

---

Gui/GUIWidget.cs

Ensure correct call to enter
Deleted redundant clear under state function
Fixed ContainsFirstUnderMouse to check current so it is right while processing mouse move event
Setting under mouse state sets parents if needed.
Made turning on off show debug bounds invalidates widget

Fixed bug with enter not having under mouse state set correctly

---

GuiAutomation/AutomationRunner.cs

- Caller expects widget to exist, by default wait for it to appear
before aborting

Revise default wait time to 5 seconds before throwing exception

---

agg/Image/ImageBuffer.cs
agg/Image/ImageTgaIO.cs

Remove event keyword from private delegate field
>private event RenderDelegate render;
Remove delegate wrapper
>FaceCount max = new FaceCount(1, e, new FaceCount.RenderDelegate(RenderTriangle));
becomes
>FaceCount max = new FaceCount(1, e, RenderTriangle);

Refactor ImageBuffer to use auto properties, throw in debug

---

PlatformWin32/win32/FileSystemStaticData.cs
PlatformWin32/win32/ImageIOWindowsPlugin.cs
agg/Image/ImageSequence.cs
agg/Image/ImageTgaIO.cs

- Remove redundant LoadImageData method
- Use File.OpenRead
- Dispose opened file streams
- Dispose opened Bitmaps
- Remove lists for sorting, use OrderBy
- Rename m_WindowsBitmap variables

Refactor image classes, FileSystemStaticData

---

Gui/FLowLeftRightWithWrapping.cs
Gui/FlowLayoutWidget.cs
Gui/Gui.csproj
Tests/Agg.Tests/Agg/WidgetClickTests.cs

Fixes:
MatterHackers/MatterControl#1859
Large amount of macros will cause some to not be visible in "Controls" panel.

	Can wrap macro buttons

---

AggTests/AggDrawingTests.cs
Gui/PerformanceTimer/PerformancePanel.cs
MarchingSquares/MarchingSquaresByte.cs
MarchingSquares/MarchingSquaresFloat.cs
PolygonMesh/Csg/CsgProcessing.cs
PolygonMesh/Net3dBool/Object3D.cs
RayTracer/RayTracer.cs
agg/Font/StyledTypeFace.cs
agg/ImageLineRenderer.cs
agg/VertexSource/Ellipse.cs
agg/VertexSource/FlattenCurve.cs
examples/GCodeVisualizer/GCodeFileLoaded.cs
examples/GCodeVisualizer/GCodeViewWidget.cs
examples/GCodeVisualizer/GCodeViewerApplication.cs
examples/SimpleDrawAndSave/SimpleDrawAndSave.csproj
examples/line_patterns/line_patterns.cs

Reduces the warning count from 32 to 16, which are now spread across the following four issues:
1. `gsv_text` is obsolete: 'All of these should use the new font stuff.  You probably want a StringPrinter or a TextWidget in this spot.' *8 warnings*
1. Unreachable code detected - *6 warnings*
1. 'Mesh' overrides Object.Equals(object o) but does not override Object.GetHashCode() - *1 warning*
1. The variable 'invokeException' is declared but never used - *1 warning*
**Remaining**

Resolve easy to address build warnings

---

GuiAutomation/AutomationRunner.cs

- Value has no effect if match is found
- Larger value gives more time for widget to appear before failing test

Update secondsToWait to match ClickByName default value (5 seconds)

---

examples/MeshViewer/MeshViewerWidget.cs

- Use object3D.Name or fall back to Path.GetFileName(this.MeshPath)
- Issue MatterHackers/MCCentral#1574
Test automation of IObject3D elements not functioning due to name mismatches

Revise name selection for FindNamedChildrenRecursive

---

Gui/Menu/OpenMenuContents.cs

- Issue MatterHackers/MCCentral#1533
Popup menus appear to leak on 1.7+ due to unreleased event listeners

Ensure popup menus are garbage collected on close

---

DataConverters3D/Object3D/IObject3D.cs
DataConverters3D/Object3D/InteractiveScene.cs
DataConverters3D/Object3D/Json/IObject3DChildrenConverter.cs
DataConverters3D/Object3D/Object3D.cs
DataConverters3D/Object3D/TextObject.cs

- All Object3D types must serialize their TypeName via IObject3D

Eliminate hard-coded type names and IMappingType marker interface

---

Gui/TabControl/Tab.cs
Gui/TabControl/TabBar.cs
Gui/TabControl/TabControl.cs

Reduce complexity of base Tab type, allowing for simpler tab implementations without the requirement of multiple widget/viewwidget objects. Move classic Tab implementation to ThreeViewTab (normal, hover, selected) and update dependants

Isolate Tab behavior in base type, extract multi-widget code to new type

---

PlatformWin32/win32/WinformsSystemWindow.cs
PlatformWin32/win32/WinformsSystemWindowProvider.cs

- Assign PlatformWindow reference as SystemWindow is shown
- Call CloseSystemWindow on owning PlatformWindow rather than local ref
- Improve naming to denote singlePlatformWindow ref used for that mode

Improve PlatformWindow provider

---

MeshThumbnails/MeshThumbnails/ThumbnailEngine.cs
MeshThumbnails/MeshThumbnails/ThumbnailTracer.cs

- Issue MatterHackers/MCCentral#2247
Thumbnail rendering hangs indefinitely on empty objects

Limit number of rescale attempts, skip thumbgen on invalid items

---

DataConverters3D/Object3D/Object3D.cs

- Give Object3D instances a chance to listen for Invadates without requiring event registration
- Issue MatterHackers/MCCentral#2276
No OnInvalidate virtual method on IObject3D instances

Add OnInvalidate to Object3D

---

DataConverters3D/Object3D/InteractiveScene.cs
DataConverters3D/Object3D/Object3D.cs
agg/agg_basics.cs

Fix crash in Transparent sorting
Improve unique name logic
Improved: MatterHackers/MCCentral#2401
Null reference exception when GetNonCollidingName param is null

Ensure selection is first to be hit by mouse

---

DataConverters3D/Object3D/Object3DExtensions.cs

issue: part of: MatterHackers/MCCentral#2286
We remember render mode between runs but don't switch to it when first run

Fixed the material index lookup

---

DataConverters3D/Object3D/InteractiveScene.cs

issue: MatterHackers/MCCentral#2664
Toolbar buttons should push focus back to View3DWidget when clicked

Make EventHandler for Focused

---

Gui/GUIWidget.cs
Gui/TextWidgets/TextWidget.cs

Clipped Text fields should use original value as ToolTipText if unset

Overridable ToolTipText, auto ToolTip when clipped

---

Gui/GUIWidget.cs
Tests/Agg.Tests/Agg.UI/ListBoxTests.cs

min size and sub-pixel size already accounted for
issue: MatterHackers/MCCentral#3149
DoubleBuffered surface created with NewGraphics2D is larger than expected

Don't need to grow the back buffer by 1

---

PlatformWin32/win32/FileSystemStaticData.cs

- Issue MatterHackers/MCCentral#3228
Make all LoadIcon signatures auto scale via DeviceScale

Automatically scale all LoadIcon calls

---

Gui/GUIWidget.cs
Gui/ResponsiveImageWidget.cs
Gui/SystemWindow/SystemWindow.cs

refactoring SetCursor to match winforms
issue: MatterHackers/MCCentral#3227
Non-image background still linked

Make responsive image cursor and click only happen on image

---

Gui/ScrollableWidget/ScrollableWidget.cs

issue: MatterHackers/MatterControl#3256
Don't consume cursor keys from scroll list if not used

Making scroll widget not consume keydowns it does not use

---

PlatformWin32/win32/WinformsSystemWindow.cs

seems to be non-destructive to test

Had a case where the agg system window was null

---

DataConverters3D/Object3D/SafeList.cs

- Issue MatterHackers/MCCentral#3518
When dragging a group of objects, the parts are not visible until
the move is completed

Set Parent reference in SafeList constructor

---

Gui/ImageSequenceWidget.cs

issue: MatterHackers/MCCentral#3568
What's New image fails to load for extended period of time

Added invalidate when resetting image index (fixed 1 frame gifs)

---

DataConverters3D/DataConverters3D.csproj
DataConverters3D/Object3D/InteractiveScene.cs
DataConverters3D/Object3D/Object3D.cs
DataConverters3D/Object3D/Object3DExtensions.cs
DataConverters3D/Object3D/SelectionGroupObject3D.cs

Making Object3D classes consistent
issue: MatterHackers/MCCentral#3702
Consider adding 'Object3D' suffix to Object3D types or use consistent format

Design tools

---

Gui/FLowLeftRightWithWrapping.cs

issue: MatterHackers/MCCentral#3805
Markdown animated gifs fail to load until explicit invalidate

Make sure we always layout FlowLeftRightWidthWrapping widget

---

Gui/TextWidgets/TextWidget.cs

- Issue MatterHackers/MCCentral#3842
Link text should have single underline rather than per word

Use widget rather than printer bounds for underline

---

Gui/TextWidgets/InternalTextEditWidget.cs

issue: MatterHackers/MCCentral#3916
Slice settings text fields should get undo data set to cleared after initial setting

Make sure we have something in the undo data when we clear it

---

DataConverters3D/AmfDocument.cs

Fix for AMF file with no whitespace that AmfDocument reads incorrectly.
ReadElementAsInt positions the reader at the start of the next element, and ReadToNextSibling then skips over that element and fails to find the sibling element in the scope. This affected the X//Y/Z nodes as well as the v1/v2/v3 nodes. This caused the entire AMF to fail loading with no valid vertices and no valid faces.
Solution is to check if the XML reader is already positioned on the expected node before calling ReadToNextSibling.

Fix for #3552 File Reader

---

DataConverters3D/Object3D/IObject3D.cs
DataConverters3D/Object3D/InteractiveScene.cs
DataConverters3D/Object3D/Object3D.cs

issue: MatterHackers/MCCentral#4229
Merge on align should not clear the colors that were on the objects
refactor apply and merge => flatten

Make flatten only copy appropriate properties by default

---

RenderOpenGl/GL/Enums/BlendingFactorDest.cs
RenderOpenGl/GL/Enums/BlendingFactorSrc.cs
RenderOpenGl/Renderer/Graphics2DOpenGL.cs

Adding in more gl blending constants
issue: MatterHackers/MCCentral#4433
Pixelated corners when using RoundedRect on draw

Fixing the blending of anti-aliasing for polygons

---

Gui/GUIWidget.cs
Gui/LayoutEngines/LayoutEngineFlow.cs
Gui/LayoutEngines/LayoutEngineSimpleAlign.cs

issue: MatterHackers/MCCentral#4457
Exit Layout function if widget.HasBeenClosed

Don't do layout if parent has been closed

---

Gui/GUIWidget.cs

issue: MatterHackers/MCCentral#4499
Allow GuiWidget.Text setter to receive null values

always ensure text is set to a valid string

---

Gui/GUIWidget.cs

- Issue MatterHackers/MCCentral#4775
Popovers appear at incorrect position in presets window

Revise TransformToScreenSpace to walk to topmost parent

---

DataConverters3D/CenterAndHeightMantainer.cs
DataConverters3D/Object3D/UndoCommands/ReplaceCommand.cs
PolygonMesh/TransformedAabbCache.cs

This would allow dragged text with up to 100 same characters (like
and 'e') not need to calculate a new aabb. All the 'e's are sharing
a mesh and the mesh has a transform for each Object3Ds position
We could make a better cache if we have some type of recency information.
Right now when we get past 100 we just clear the list. We would be a 
lot faster if we kept the last 100 hits and then removed non-hit data
at some rate.
issue: MatterHackers/MCCentral#4951
Make AABB cache hold n items

Made the mesh aabb cache hold up to 100 matrix caches

---

agg/VertexSource/VertexStorage.cs

Fixes observed exception with `Freesample.svg`

Ensure NextElementIsANumber false when parseIndex == dString.Length

---

RenderOpenGl/GLMeshTrianglePlugin.cs

When creating sub-meshes for a given mesh in the gl render data,
switch to a new one if we are going from a texture group to a non-texture group
issue: MatterHackers/MCCentral#5331
Bed mesh no longer detectable

create new sub mesh when switch from a textured to non-textured

---

DataConverters3D/Object3D/Json/IObject3DContractResolver.cs

- Issue MatterHackers/MCCentral#5359
Conditional Matrix serialization should not be exact to
Matrix4X4.Identity

Only serialize Matrix values off by more than .001

---

Gui/GUIWidget.cs

- Issue MatterHackers/MCCentral#5391
Unable to close MatterControl when submenus are open

Close last child until none remain

---

agg/Font/StyledTypeFace.cs

This change is due to the fix in the IVertex source bounds being right.
They used to always start at 0,0 and that was a bug that this code had
taken a dependency on.
issue: MatterHackers/MCCentral#5506
Terminal incorrectly reports line sent

The font cache was expecting the bounds to start at 0

---

DataConverters3D/Object3D/SelectedChildren.cs

- Issue MatterHackers/MCCentral#5565
MatterControl extra slow with specific MCX, crashes on copy

Use HashSet for SelectedChildren

---

PolygonMesh/Processors/MeshConvexHull.cs

- Issue MatterHackers/MCCentral#5646
InvalidOperationException: Collection was modified; enumeration
operation may not execute.

Iterate on copy to prevent collection modified exception

---

Gui/ScrollableWidget/ScrollableWidget.cs

issue: MatterHackers/MCCentral#5723
Tree view shifting when user selecting nodes

don't scroll into view a control that is already in view

---

Typography/Typography.OpenFont/Tables/OS2.cs

Hey!
I noticed that version 0 fonts didn't render at all, I did some debuging and I found that the OS2 table was read incorrectly.
I found the correct definitions here:
https://docs.microsoft.com/en-us/typography/opentype/spec/os2

OS2 version 0 Fix

---

GuiAutomation/AutomationRunner.cs

This part of a fix for MatterControl issue MatterHackers/MatterControl#5198. It lets the automation harness dismiss the save changes dialog that pops up for some tests when the main application is closed.

Pass test runner to close action

---

GuiAutomation/AutomationRunner.cs

This should have been included in pull request #1458 to make it more obvious when watching the automated tests to see which clicks are control-clicks.

Display modifiers on automation mouse clicks

---

PlatformWin32/win32/OpenGLSystemWindow.cs

The automation tests bypass the native platform eventing to synthesize
keyboard events. However, not all operations in MatterControl look directly
at the keyboard state but instead rely on the ModifierKeys property of the
system window. Therefore, the automation tests must both set the keyboard
state and the modifier keys on the system window.
This goes with the PR for   MatterHackers/MatterControl#5188

Allow automation tests to override modifiers on OpenGL system window

---

Gui/Animation.cs
PolygonMesh/Mesh.cs
PolygonMesh/RayTracer/Primitive/Shapes/PlaneShape.cs
RenderOpenGl/WorldViewExtensions.cs
Tests/Agg.Tests/Agg.VectorMath/VectorMathTests.cs
VectorMath/AxisAlignedBoundingBox.cs
VectorMath/WorldView.cs

Mostly rewriting WorldView. Should remain compatible with the existing implementation, unless `GetWorldPosition` is used.
* Rewritten `CalculateOrthogrphicMatrixOffCenter`.
* Magic constants are named now.
* `EyePosition` can be set.
* Projection transform is updated even if the viewport size is zero.
* Some extra tests for `WorldView`.
This is a dependency of the PR for MatterControl.
Part of the solution for issue https://github.com/MatterHackers/MatterControl/issues/5187.

Changes for orthographic view mode

---

PolygonMesh/DualContouring/Octree.cs
PolygonMesh/DualContouring/SVD.cs
PolygonMesh/DualContouring/Schur2.cs
Tests/Agg.Tests/Agg.PolygonMesh/MeshTests.cs

This is my proposal to fix MatterHackers/MatterControl#5193.
It fixes some errors in the implementation and improves function `ApproximateZeroCrossingPosition` by including a linear interpolation in addition to the existing incremental search.

Fix dual contouring implementation
